%% the smile gaussian
clc
clear
close all

N=128;         %the number of sampled point for a single gaussian distribution
t1=-5;t2=5;
T=(t2-t1);            % Sampling interval
F0=1/T;               % Minimum frequency interval
Fs=(N-1)*F0;          % Sampling frequency
[X,Y]=meshgrid((-N/2:N/2-1)*T/N,(-N/2:N/2-1)*T/N);
wx=(-N/2:N/2-1)*2*pi*Fs/N;
wy=wx;
[WX,WY]=meshgrid(wx,wy);
%d=(t2-t1)/(n-1);
%[X,Y]=meshgrid(t1:d:t2,t1:d:t2);%range of x and y
f=zeros(N,N);%matrix to store the sum of each part of gaussian distribution

%the outline of the face
sigma1=[0.05 0;0 0.05];%covariance of the outline and the mouse of face
n1=100;%number of total gaussian distribution for the outline
dtheta1=2*pi/n1;
theta1=0:dtheta1:2*pi-dtheta1;
r1=4.5;
mu1=zeros(n1,2);
mu1(:,1)=cos(theta1)*r1;
mu1(:,2)=sin(theta1)*r1;
for j=1:n1
    ft=1.5*mvnpdf([X(:) Y(:)],mu1(j,:),sigma1); 
    f=f+reshape(ft,size(X));
end

%the mouth
n2=21; 
mouth1=7*pi/6; mouth2=11*pi/6;
dtheta2=(mouth2-mouth1)/(n2-1);
theta=mouth1:dtheta2:mouth2;
r2=3;
mu2=zeros(n2,2);
mu2(:,1)=cos(theta)*r2;
mu2(:,2)=sin(theta)*r2;
for j=1:n2
    ft=1.5*mvnpdf([X(:) Y(:)],mu2(j,:),sigma1); 
    f=f+reshape(ft,size(X));
end

%the eyes
sigma2=sigma1*10; %covariance of the eyes
eyeleft=[-1.8,1];
eyeright=[1.8,1];
ft=30*mvnpdf([X(:) Y(:)],eyeleft,sigma2); %times 30 here to make it seems darker for sigma2 here is larger than sigma1
f=f+reshape(ft,size(X));
ft=30*mvnpdf([X(:) Y(:)],eyeright,sigma2); 
f=f+reshape(ft,size(X));

%eye outline
sigma3=sigma1*0.8;
n3=20;
mu3=zeros(n3,2);
mu4=mu3;
dtheta3=2*pi/n3;
theta3=0:dtheta3:2*pi-dtheta3;
r3=1.2;
mu3(:,1)=eyeleft(1)+cos(theta3)*r3;
mu3(:,2)=eyeleft(2)+sin(theta3)*r3;
mu4(:,1)=eyeright(1)+cos(theta3)*r3;
mu4(:,2)=eyeright(2)+sin(theta3)*r3;
for j=1:n3
    ft1=1.2*mvnpdf([X(:) Y(:)],mu3(j,:),sigma3); 
    ft2=1.2*mvnpdf([X(:) Y(:)],mu4(j,:),sigma3);
    f=f+reshape(ft1,size(X))+reshape(ft2,size(X));
end

% f is the gaussian function of the smile(discrete)

%% analytical Fourier in cartesian

G_ana_comp=zeros(N,N);
for i=1:N
    for j=1:N
        WXY=[WX(i,j),WY(i,j)];           
        G_ana_comp(i,j)=sum(1.5*exp(-0.5*WXY*sigma1*WXY'-1i*WXY*(mu1')))... % face outline       
                       +sum(1.5*exp(-0.5*WXY*sigma1*WXY'-1i*WXY*(mu2')))...% mouth
                       +30*exp(-0.5*WXY*sigma2*WXY'-1i*WXY*(eyeleft'))...%lefteye
                       +30*exp(-0.5*WXY*sigma2*WXY'-1i*WXY*(eyeright'))...%righteye
                       +sum(1.2*exp(-0.5*WXY*sigma3*WXY'-1i*WXY*(mu3')))...%for left eye outline
                       +sum(1.2*exp(-0.5*WXY*sigma3*WXY'-1i*WXY*(mu4')));%for right eye outline        
    end 
end

G_ana_abs=abs(G_ana_comp);
figure(1);
surf(WX,WY,G_ana_abs);
axis([-5 5 -5 5 0 300])
shading interp
xlabel('w1');ylabel('w2');zlabel('Magnitude');
title('Analytical FT - Magnitude');

%% FFT in cartesian

G_fft_comp=fftshift(fft2(f))*T^2/N^2;
for i=1:N 
    for j=1:N
        G_fft_comp_m(i,j)=G_fft_comp(i,j)*exp(-1i*pi*(i-1)-1i*pi*(j-1)); %modify the phase
    end 
end
G_fft_abs=abs(G_fft_comp_m);
figure(2)
surf(WX,WY,G_fft_abs)
shading interp
xlabel('w1');ylabel('w2');zlabel('Magnitude');
title('FFT - Magnitude')

figure(3)
error_mag=G_ana_abs-G_fft_abs;
surf(WX,WY,abs(error_mag))
shading interp
xlabel('w1');ylabel('w2');zlabel('Error');
title('Error between Analytical and FFT - Magnitude')

%% Polar FFT

% directly from discrete time signal in cartesian to discrete frequency in polar

OS1=5;OS2=5; %oversampling, errors reduce with OS increase
G_pfft=My_PFFT(f,OS1,OS2); %get from a paper
G_pfft=G_pfft*T^2/N^2;

figure(4)
[X_polar,Y_polar]=Create_Grid('X',[N,pi*Fs],'r.'); % Polar grid, generated by warping the recto-polar along angles and then rays
[theta_W,rho_W]=cart2pol(X_polar,Y_polar);

figure(5)
surf(X_polar,Y_polar,abs(G_pfft))
%pcolor(X_polar,Y_polar,abs(G_pfft));
shading interp

figure(6)
surf(theta_W,rho_W,abs(G_pfft));
shading interp


%% polar analytical

G_ana_polar=zeros(2*N,2*N);
for i=1:2*N
    for j=1:2*N
        WXY_polar=[X_polar(i,j),Y_polar(i,j)];           
        G_ana_polar(i,j)=sum(1.5*exp(-0.5*WXY_polar*sigma1*WXY_polar'-1i*WXY_polar*mu1'))... % face outline       
                       +sum(1.5*exp(-0.5*WXY_polar*sigma1*WXY_polar'-1i*WXY_polar*mu2'))...% mouth
                       +30*exp(-0.5*WXY_polar*sigma2*WXY_polar'-1i*WXY_polar*eyeleft')...%lefteye
                       +30*exp(-0.5*WXY_polar*sigma2*WXY_polar'-1i*WXY_polar*eyeright')...%righteye
                       +sum(1.2*exp(-0.5*WXY_polar*sigma3*WXY_polar'-1i*WXY_polar*mu3'))...%for left eye outline
                       +sum(1.2*exp(-0.5*WXY_polar*sigma3*WXY_polar'-1i*WXY_polar*mu4'));%for right eye outline        
    end 
end

figure(7)
surf(X_polar,Y_polar,abs(G_ana_polar))
%pcolor(X_polar,Y_polar,abs(G_ana_polar));
shading interp

figure(8)
surf(theta_W,rho_W,abs(G_ana_polar));
shading interp


%%

figure(9)
surf(theta_W,rho_W,abs(G_pfft)-abs(G_ana_polar));
shading interp
